services:
  db:
    image: postgres:16
    container_name: ticketing-db
    environment:
      POSTGRES_DB: ticketing
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: ticket
    ports: ["5432:5432"]
    volumes: [ "db_data:/var/lib/postgresql/data" ]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ticket -d ticketing"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketing-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticketing
      SPRING_DATASOURCE_USERNAME: ticket
      SPRING_DATASOURCE_PASSWORD: ticket
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"


  pgadmin:
    image: dpage/pgadmin4:8
    container_name: ticketing-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com   # <-- değiştir
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
