apiVersion: v1
kind: Secret
metadata:
  name: ticketing-secrets
  namespace: ticketing
type: Opaque
stringData:
  POSTGRES_DB: ticketing
  POSTGRES_USER: ticket
  POSTGRES_PASSWORD: ticketpw
  PGADMIN_PASSWORD: admin123
